### ISSUE TITLE
Error: can raise an unlisted exception: ref OSError

### ISSUE THREAD

**Issue by cloudify** [FedericoCeratto/nim-syslog#3]
Hi there,

thanks for developing this integration with syslog (apparently it's the only one available for Nim).
I've just tried to add this library to a project (using Nim 0.15.0) and I'm getting the following error when compiling the syslog library:

```
~/.nimble/pkgs/syslog-0.0.1/syslog.nim(197, 28) template/generic instantiation from here
lib/pure/os.nim(151, 3) Error: can raise an unlisted exception: ref OSError
```

Any idea on the cause / solution?

thanks

**Comment by FedericoCeratto** [comment]
Thanks for the bug report. Looks like closelog() could raise OSError while it's flagged as not raising any exception. I cannot reproduce the issue using Nim  0.13.0 ,  0.14.2 and 0.15.2 - can you try the same compiler version? Otherwise, what flags are you using to compile your code? Can you reproduce the failure by compiling the example code in the readme alone?

**Comment by cloudify** [comment]
I just compiled nim-0.15.2 and tried to compile the example code with it:

```
% ~/tmp/nim-0.15.2/bin/nim --lib=~/tmp/nim-0.15.2/lib c test_syslog.nim
Hint: used config file '/Users/federico/tmp/nim-0.15.2/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test_syslog [Processing]
Hint: syslog [Processing]
Hint: posix [Processing]
Hint: times [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: os [Processing]
/Users/federico/.nimble/pkgs/syslog-0.0.1/syslog.nim(197, 28) template/generic instantiation from here
lib/pure/os.nim(151, 3) Error: can raise an unlisted exception: ref OSError
```

The content of `test_syslog.nim` is:

```nim
import syslog

syslog.openlog("MyApp", logUser)  # optional
syslog.info("Good news")
syslog.debug("Psst")
syslog(logAlert, "Alert!")
syslog.closelog()  # optional
```

**Comment by cloudify** [comment]
Just tried with nim-0.15.2 installed via homebrew, same error:

```
% nim c test_syslog.nim
Hint: used config file '/usr/local/Cellar/nim/0.15.2/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test_syslog [Processing]
Hint: syslog [Processing]
Hint: posix [Processing]
Hint: times [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: os [Processing]
/Users/federico/.nimble/pkgs/syslog-0.0.1/syslog.nim(197, 28) template/generic instantiation from here
lib/pure/os.nim(151, 3) Error: can raise an unlisted exception: ref OSError
```

**Comment by FedericoCeratto** [comment]
@cloudify I suspect the issue happens only on OSX. The library should not throw exceptions. Can you tell which functions in closelog() are capable of throwing it? You can just comment out some of the functions and recompile to spot the culprit

**Comment by cloudify** [comment]
@FedericoCeratto it seems the origin of the exception is `getAppFilename()` called by `closelog() -> closeLogInternal() -> appName()`

**Comment by FedericoCeratto** [comment]
https://github.com/FedericoCeratto/nim-syslog/blob/master/syslog.nim#L103  this should catch OSError as well looks like

**Comment by cloudify** [comment]
Ok I think I found the origin, and is indeed `macosx` dependent:

in `os.getAppFilename()`:

```nim
# ...
elif defined(macosx):
    var size: cuint32
    getExecPath1(nil, size)
    result = newString(int(size))
    if getExecPath2(result, size):
      result = "" # error!
    if result.len > 0:
      result = result.expandFilename
# ...
```

`expandFilename` is used only for `macosx` and it raises `OSError`:

```nim
# ...
proc expandFilename*(filename: string): string {.rtl, extern: "nos$1",
  tags: [ReadDirEffect].} =
  ## Returns the full (`absolute`:idx:) path of the file `filename`, raises OSError in case of an error.
# ...
```

`OSError` is not catched by the `try` block since [IndexError](http://nim-lang.org/docs/system.html#IndexError) derives from `Exception` and [OSError](http://nim-lang.org/docs/system.html#OSError) derives from `SystemError`.

**Comment by cloudify** [comment]
PR #4 adds catch of `OSError` in `appName()`
