### ISSUE TITLE
Issues with nimble errors and warnings.

### ISSUE THREAD

**Issue by treeform** [FedericoCeratto/nim-syslog#7]
Nimble complains about these things:
* You have README.md listed in the installed file, but don't have README.md but have README.adoc, could you update the instructions in the nimble file?
```
nimble check -n
    Prompt: Missing file /p/nimwatch/pkgs/syslog/README.md. Continue? -> [forced no]
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Could not validate package:
```
* `nimble` recommends a different package structure. some thing like:
```
syslog.nim
syslog/*others*.nim
```

Also:
* nim-syslog is not valid package name. Would you please rename the repo to just syslog? 
* You have tests. Thats great! Could you add that to a `nimble test` targets so that nimble can run them?
* Everyone seems to use README.md. Would you please convert README.adoc to README.md?

**Comment by treeform** [comment]
Sorry update, its not nimble.exe that requires the README.md, but the syslog.nimble file.

**Comment by FedericoCeratto** [comment]
Fixed, thanks.
